# Generated by Django 5.1.15 on 2026-04-29 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEUI', models.CharField(max_length=64, unique=True)),
                ('latest_status', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.PositiveIntegerField()),
                ('data_hex', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=16)),
                ('rx_info', models.JSONField(blank=True, default=list)),
                ('tx_info', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='devices.device')),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('device', 'fCnt')},
            },
        ),
    ]
